version: '3'
services:
  syms_marketplace:
    restart: always
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn syms_marketplace.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/usr/src/syms_marketplace/staticfiles
      - media_volume:/usr/src/syms_marketplace/mediafiles
    ports:
      - 8000:8000
    env_file:
      - syms_marketplace/.env
    depends_on:
      - postgresql_db
  postgresql_db:
    restart: always
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build:
      context: ./config/nginx
      dockerfile: Dockerfile
    volumes:
      - static_volume:/usr/src/syms_marketplace/staticfiles
    ports:
      - 80:80
    depends_on:
      - syms_marketplace
volumes:
  postgres_data:
  static_volume:
  media_volume:
