version: '3'

services:
  syms_marketplace:
    build:
      context: ./
      dockerfile: Dockerfile
    command: gunicorn Marketplace_Django_DRF_Vue.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./Marketplace_Django_DRF_Vue/.env
    depends_on:
      - postgresql_db
  postgresql_db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: config/nginx/Dockerfile
    ports:
      - 1337:80
    depends_on:
      - syms_marketplace

volumes:
  postgres_data: